SAJ/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from a_user_management.views import send_code

urlpatterns = [
    path('admin/', admin.site.urls),

    path('authentication/', include('a_user_management.urls')),
    path('courses/', include('a_course_management.urls')),
    path('', include('a_notification_management.urls')),
    path('branch', include('a_institution_management.urls')),


    path('send-code/', send_code, name='send_code'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_course_management/models.py
from django.db import models
import jdatetime # type: ignore
from a_user_management.models import Teacher, Student
from decimal import Decimal
from a_institution_management.models import Branch
from django.core.exceptions import ValidationError
# Create your models here.




class Course(models.Model):

    INSTALLMENT = [
        ('0','ندارد'),
        ('1','دارد'),
    ]

    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True, related_name='courses')
    title = models.CharField(max_length=255, null=True, verbose_name='نام دوره')
    prerequisites = models.ManyToManyField('Course', related_name='required_for',blank=True, verbose_name='پیشنیاز ها') # math101.required_for.all()  # Returns [math102]
    course_img = models.ImageField(upload_to='Course_images/',blank=True, null=True, verbose_name='تصویر دوره')
    price = models.IntegerField(default=0, null=True, verbose_name='(تومان)  قیمت')
    installment = models.CharField(default=0,max_length=1,choices=INSTALLMENT, null=True, blank=True, verbose_name='اقساط')
    courseDuration = models.CharField(max_length=63, null=True , blank=True, verbose_name='تعداد جلسات دوره')
    session_length = models.CharField(max_length=63, null=True , blank=True, verbose_name='مدت زمان هر جلسه (ساعت)')
    course_hours = models.IntegerField(default=10, null=True, verbose_name='تعداد ساعت دوره (ساعت)')
    description = models.TextField(max_length=2047, null=True , blank=True, verbose_name='توضیحات')
    
    class Meta:
        verbose_name = "دوره"  # Singular name for admin
        verbose_name_plural = "2- دوره ها"  # Plural name for admin

    def __str__(self):
        return self.title
    
class Section(models.Model):


    TYPE = [
        ('0','اتمام مهلت ثبت نام'),
        ('1','در حال ثبت نام'),
        
    ]
    METHOD = [
        ('0','حضوری'),
        ('1','آنلاین'),
        
    ]

    GENDER = [
        ('0','دخنر'),
        ('1','پسر'),
        ('2','مختلط'),
    ]

    name = models.CharField(max_length=63, null=True, blank=True, verbose_name='گروه') #or section number
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, related_name='sections', null=True, blank=True, verbose_name='دوره')
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, related_name='sections', null=True, blank=True, verbose_name='استاد')
    students = models.ManyToManyField(Student, through='SectionStudent', related_name='sections', verbose_name='دانشجو ها')
    method = models.CharField(max_length=1, default=0,choices=METHOD, verbose_name='نحوه برگزاری')
    capacity = models.IntegerField(null=True, blank=True, default=1, verbose_name='ظرفیت')
    section_status = models.CharField(default=1, max_length=1, choices=TYPE, verbose_name='وضعیت')
    session_number = models.IntegerField(null=True, blank=True, default=0, verbose_name=' تعداد جلسات برگزار شده ')
    gender = models.CharField(max_length=1, null=True, blank=True, choices=GENDER, verbose_name="جنسیت")
    start_date = models.DateField(verbose_name='تاریخ شروع', null=True)


    @property
    def registered(self):   
        return self.section_students.filter(activity='0').count()

    class Meta:
        verbose_name = "گروه"
        verbose_name_plural = "3- گروه ها" 

    def __str__(self):
        return f'{self.course.title} - {self.teacher} | {self.name}'
    
#  THIS IS A INTERMEDIATE CLASS FOR SHOWING STUDENT IN ADMIN PANEL OF SECTION, I COUDNT SHOW THEM DIRECTLY
#  I HAD TO USE  through='SectionStudent' AND THAT WAS ACHIVABLE WITH AN  Intermediary Model LIKE THIS
#  IT ALSO REPERESENT STUDENT IN SECTION LINK THAT CONTAINS SOME INFORMATION UNIQUE TO STUDENT AND SECTION 
#  THAT HES BELONG TO LIKE HIS SCORE IN THAT SECTION

class SectionStudent(models.Model):


    


    ACTIVITY = [
        ('0','در حال تحصیل'),
        ('1','دوره پایان یافته | قبول'),
        ('2','دوره پایان یافته | مردود'),

    ]

    section = models.ForeignKey(Section, on_delete=models.SET_NULL,related_name='section_students', verbose_name='گروه', null=True)
    student = models.ForeignKey(Student, related_name='section_students', on_delete=models.SET_NULL, verbose_name='دانشجو', null=True)
    activity = models.CharField(default=0,max_length=1,choices=ACTIVITY, verbose_name="وضعیت دانشجو در این دوره")

    date_joined = models.DateField(auto_now_add=True)  # Additional fields
    class_score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name='نمره کلاسی')
    exam_score = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True, verbose_name='نمره پایانی')
    start_date = models.DateField(verbose_name='تاریخ شروع', null=True, blank=True)
    end_date = models.DateField(verbose_name='تاریخ پایان', null=True, blank=True)
    # you ask question about when this date should register

    # financial informations
    dept = models.IntegerField(blank=True, null=True, verbose_name='(تومان) مانده بدهی')



    @property
    def score(self):
        if self.class_score and self.exam_score:
            score = (Decimal('0.7') * self.class_score) + (Decimal('0.3') * self.exam_score)
            return (f'{score}')
        return "بدون نمره"

    class Meta:
        verbose_name = "دوره برای دانشجو" 
        verbose_name_plural = "1- اطلاعات تحصیلی" 


    def clean(self):
        """
        Custom validation to ensure only one active student in the same section.
        """
        if self.activity == '0':
            # Check for existing '0' activity for the same student in the same section
            existing = SectionStudent.objects.filter(
                section=self.section, 
                student=self.student, 
                activity='0'
            ).exclude(id=self.id)  # Exclude the current instance if editing
            if existing.exists():
                raise ValidationError(" دانشجو در این گروه اکنون با وضعیت 'در حال تحصیل' ثبت شده است.")
            
        # Check for student debt only when creating a new instance
        if not self.id and (self.student.total_dept_from_courses > 0 or self.student.balance < 0):
            raise ValidationError(" دانشجو بدهی تصفیه نشده دارد")


    def save(self, *args, **kwargs):
        """
        Override save to ensure `clean` is called.
        """
        self.full_clean()  # Ensures `clean` is called before saving
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f'{self.student} در {self.section}'
    

from django.db.models.signals import pre_save
from django.dispatch import receiver
@receiver(pre_save, sender=SectionStudent)
def update_dept(sender, instance, **kwargs):
    if not instance.pk:  # Only for new instances (pk doesn't exist yet)
        if instance.section and instance.section.course:
            instance.dept = instance.section.course.price


class SectionTimeSlot(models.Model):

    DAYS_OF_WEEK = [
        ('0','شنبه'),
        ('1','یکشنبه'),
        ('2','دوشنبه'),
        ('3','سه شنبه'),
        ('4','چهارشنبه'),
        ('5','پنجشنبه'),
        ('6','جمعه'),
        
    ]


    section = models.ForeignKey(Section, on_delete=models.SET_NULL, related_name='time_slots', verbose_name='گروه', null=True)
    day_of_week = models.CharField(max_length=1, choices=DAYS_OF_WEEK, verbose_name='روز')  # Store the selected day
    timeOfSection = models.CharField(max_length=127, null=True, verbose_name='زمان')
    place = models.CharField(max_length=63, null=True, verbose_name='مکان')
    class Meta:
        verbose_name = "زمان سکشن"
        verbose_name_plural = "زمان سکشن ها" 

    def __str__(self):
        return f"{self.section.course.title} | {self.section.teacher} | {self.section.name} | ({self.day_of_week} : {self.timeOfSection})"

    
class Attendance(models.Model):
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, related_name='attendances', null=True, blank=True, verbose_name='سکشن')
    section_student = models.ForeignKey(SectionStudent,related_name='attendances', on_delete=models.SET_NULL, verbose_name='دانشجو', null=True)
    date = models.CharField(max_length=63, null=True, blank=True, verbose_name='تاریخ')  
    status = models.BooleanField(default=False, verbose_name='وضعیت')
    grg_date = models.DateField(auto_now_add=True, verbose_name='تاریخ')
    session = models.CharField(default='جلسه 1', max_length=31, null=True, blank=True, verbose_name='جلسه')

    class Meta:
        verbose_name = "حضور غیاب ها" 
        verbose_name_plural = "4- حضور غیاب" 


class Exam(models.Model):
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, related_name='exam', null=True, blank=True, verbose_name='گروه')
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, related_name='exams', null=True, blank=True, verbose_name='استاد')

    exam_time = models.DateTimeField(verbose_name='تاریخ آزمون')

    class Meta:
        verbose_name = "آزمون" 
        verbose_name_plural = "8- آزمون ها" 
    
    def __str__(self):
        return f'آزمون برای {self.section.course.title} | {self.teacher} | {self.section.name}'

class HomeWork(models.Model):
    title = models.CharField(max_length=127, null=True, blank=True, verbose_name='عنوان')
    pdf = models.FileField(upload_to='GivenHomeWorks/files/', verbose_name='فایل پیوست', null=True , blank=True)  # 'documents/pdfs/' is the upload path
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, related_name='homeworks', null=True, blank=True, verbose_name='گروه')
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, related_name='homeworks', null=True, blank=True, verbose_name='استاد')
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)  
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    expire_time = models.DateTimeField(verbose_name='مهلت تحویل')
    description = models.TextField(max_length=2047, null=True , blank=True, verbose_name='توضیحات')

    
    class Meta:

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}APhome{% endblock %}</title>
    {% load static %}
    <!-- Global CSS (like your base styles) -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="../media/education_graduate_college_university_cap_graduation_icon_262277.ico" type="image/x-icon">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Material+Icons+Round'>
    <!-- Additional CSS for individual pages can be added here -->
    {% block extra_css %}{% endblock %}
</head>
<body>

    <!-- Navbar -->
    <header>
        <nav id="navbar">
            <ul class="navbar-items flexbox-col">
              <li class="navbar-logo flexbox-left">
                
                <a class="navbar-item-inner flexbox">
                  <svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1" viewBox="0 0 1438.88 1819.54">
                    <polygon points="925.79 318.48 830.56 0 183.51 1384.12 510.41 1178.46 925.79 318.48"/>
                    <polygon points="1438.88 1663.28 1126.35 948.08 111.98 1586.26 0 1819.54 1020.91 1250.57 1123.78 1471.02 783.64 1663.28 1438.88 1663.28"/>
                  </svg>
                </a>

                <p class="link-text" style="font-size: 16px; text-align: right;"><a href="{% url 'home_url' %}" style="color: #DFF5FF;">خانه برنامه نویسان اهواز</a></p>
              </li>
              {% if request.user.is_authenticated %}
                  <li class="navbar-item flexbox-left">
                      <a href="#" class="navbar-item-inner flexbox-left">
                          <div class="navbar-item-inner-icon-wrapper flexbox">
                              <img class="small-profile" src="{% static 'media/default_profile.png' %}">
                          </div>
                          <span class="link-text">{{ request.user.first_name }} {{ request.user.last_name }}</span>
                      </a>
                  </li>
              {% endif %}

              <li class="navbar-item flexbox-left">
                <a href="{% url 'courses_url' %}" class="navbar-item-inner flexbox-left">
                  <div class="navbar-item-inner-icon-wrapper flexbox">
                    <img class="icon" src="{% static 'media/icons/course.png' %}" alt="">
                  </div>
                  <span class="link-text">دوره ها</span>
                </a>
              </li>
              <li class="navbar-item flexbox-left">
                <a href="{% url 'my-courses_url' %}" class="navbar-item-inner flexbox-left">
                  <div class="navbar-item-inner-icon-wrapper flexbox">
                    <img class="icon" src="{% static 'media/icons/flow-chart.png' %}" alt="">
                  </div>
                  <span class="link-text">کلاس های من</span>
                </a>
              </li>
              
              <!-- <li class="navbar-item flexbox-left">
                <a class="navbar-item-inner flexbox-left">
                  <div class="navbar-item-inner-icon-wrapper flexbox">
                    <img class="icon" src="{% static 'media/icons/weekly.png' %}" alt="">
                  </div>
                  <span class="link-text">برنامه کلاس ها</span>
                </a>
              </li> -->

              <!-- <li class="navbar-item flexbox-left">
                <a class="navbar-item-inner flexbox-left">
                  <div class="navbar-item-inner-icon-wrapper flexbox">
                    <img class="icon" src="{% static 'media/icons/exams.png' %}" alt="">
                  </div>
                  <span class="link-text">برنامه امتحانات</span>
                </a>
              </li> -->

              <li class="navbar-item flexbox-left">
                <a href="{% url 'my_degrees_url' %}" class="navbar-item-inner flexbox-left">
                  <div class="navbar-item-inner-icon-wrapper flexbox">
                    <img class="icon" src="{% static 'media/icons/a-.png' %}" alt="">
                  </div>
                  <span class="link-text">کارنامه</span>
                </a>
              </li>
              <li class="navbar-item flexbox-left">
                <a href="{% url 'my_financial_url' %}" class="navbar-item-inner flexbox-left">
                  <div class="navbar-item-inner-icon-wrapper flexbox">
                    <img class="icon" src="{% static 'media/icons/money-transfer.png' %}" style="scale: 1.2;" alt="">
                  </div>
                  <span class="link-text">اطلاعات مالی</span>
                </a>
              </li>
              <li class="navbar-item flexbox-left">
                <a href="{% url 'logout_url' %}" class="navbar-item-inner flexbox-left">
                  <div class="navbar-item-inner-icon-wrapper flexbox">
                    <img class="icon" src="{% static 'media/icons/log-out.png' %}" style="scale: 1.1;" alt="">
                  </div>
                  <p class="link-text" style="text-align: right;">خروج</p>
                </a>
              </li>
            </ul>
          </nav>
    </header>

    <!-- Main content area -->
    <main>
      {% if messages %}
      <div class="messages" id="messages">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}" role="alert">
            <h3 style="margin: 0 auto;">{{ message }}</h3>
          </div>
        {% endfor %}
      </div>
      {% endif %}
        
        {% block content %}
        <div class="box">
          <h1>خطا</h1>


        </div>
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer>
        <p>© 2024 My Website. All rights reserved.</p>
    </footer>


    <!-- Additional JS for individual pages can be added here -->
    {% block extra_js %}{% endblock %}
    <!-- Global JS (like common scripts) -->
    <script src="{% static 'js/base.js' %}"></script>
    
    

</body>
</html>

templates/copy.html
{% extends 'base.html' %}

{% block title %}
    Home - My Website
{% endblock %}
{% load static %}


{% block extra_css %}
    <style></style>
{% endblock %}


{% block content %}
    <h1>Welcome to the Home Page!</h1>
    <p>This is the home page content that is unique to this view.</p>
{% endblock %}


{% block extra_js %}
    <script></script>
{% endblock %}

templates/course.html
{% extends 'base.html' %}

{% block title %}
    APhome | Courses
{% endblock %}
{% load static %}


{% block extra_css %}
    <style></style>
{% endblock %}


{% block content %}
    <form action="" method="POST" style="width: 100%;">
        {% csrf_token %}
        <div class="filter-box">
            <div class="user-box">
                <input type="text" name="username" required>
                <label> جستوحو در دوره ها</label>
            </div>
            <button class="button" type="submit">جستوحو</button>

        </div>
    </form>
    <div class="courses-wrapper">
        {% for course in courses %}
        <div class="course">
            {% if course.course_img %}
                <img src="{{ course.course_img.url }}" alt="{{ course.title }}">
            {% else %}
                <img src="{% static 'media/no-course-image' %}" alt="{{ course.title }}">
            {% endif %}
            
            <h1>{{ course.title }}</h1>
            <p>{{ course.description|default:"No description available" }}</p>
            
            <h5 style="padding: 0 10px;">وضعیت: 
                {% if course.course_status == '1' %}
                    در حال ثبت نام
                {% else %}
                    اتمام مهلت ثبت نام
                {% endif %}
            </h5>
            
            <a class="button" href="{% url 'course_detail_url' course.pk %}">جزییات</a>
        </div>
        {% endfor %}
        
    </div>
{% endblock %}


{% block extra_js %}
    <script></script>
{% endblock %}

templates/course_detail.html
{% extends 'base.html' %}

{% block title %}
    Home - My Website
{% endblock %}
{% load static %}


{% block extra_css %}
    <style></style>
{% endblock %}


{% block content %}
    <div class="course-detail">
        {% if course.course_img %}
            <img src="{{ course.course_img.url }}" alt="{{ course.title }}">
        {% else %}
            <img src="{% static 'default_course_image.jpg' %}" alt="{{ course.title }}">
        {% endif %}
        
        <h1>{{ course.title }}</h1>
        <p style="padding: 25px;">{{ course.description|default:"No description available" }}</p>
        <div style="width: fit-content; display: flex; flex-direction: row; justify-content: right; align-items: center; margin-left: auto; margin-right: 20px;">
            <p> پیش نیاز های دوره : </p>
            {% for prerequisite in course.prerequisites.all %}
            <p class="course-details-prerequisites">{{prerequisite.title}}</p>
            {% endfor %}

        </div>
        <div class="course-details-info">
            <p>وضعیت : 
                {% if course.course_status == '1' %}
                    در حال ثبت نام
                {% else %}
                    اتمام مهلت ثبت نام
                {% endif %}
            </p>
    
            <p>هزینه دوره : {{course.price}}</p>
            <p> شرایط اقساط : {% if course.installment == '1' %} ندارد {% elif course.installment == '0' %} دارئ {% else %} نامشخص {% endif %}</p>
            <p>مدت زمان دوره : {{ course.courseDuration }} </p>
        </div>
        <div class="section-box">
            <div class="section-row section-header">
                <div class="section-cell">شماره سکشن</div>
                <div class="section-cell">استاد سکشن</div>
                <div class="section-cell">ظرفیت</div>
                <div class="section-cell">ظرفیت باقی مانده</div>
                <div class="section-cell"> زمان سکشن</div>            
                <div class="section-cell">لینک ثبت نام</div>
            </div>

            <!-- Data Row 1 -->
             {% for section in course.sections.all %}
            <div class="section-row">
                <div class="section-cell">{{ forloop.counter }}</div>
                <div class="section-cell">{{section.teacher.first_name}} {{section.teacher.last_name}}</div>
                <div class="section-cell">{{section.capacity}}</div>
                <div class="section-cell">{{section.registered}}</div>
                <div class="section-cell"><a href="#" class="button show-dialog" style="padding: 5px 15px;" data-section-id="{{ section.id }}"
                    data-info="
                    
                    ">زمان</a>
                </div>
                <div id="timeslot-info-{{ section.id }}" style="display: none;">
                    {% for timeslot in section.time_slots.all %}
                    {{timeslot.day_of_week}} {{timeslot.timeOfSection}} {{timeslot.place}}<br>
                    {% endfor %}
                </div>
                <div class="section-cell"><a href="" class="button" style="padding: 5px 15px;">ثبت نام</a></div>

            </div>
            {% endfor %}
            
                <!-- Dialog Box -->
            <div id="dialog" class="dialog">
                <div class="dialog-content">
                <span class="close-button">&times;</span>
                <h2>زمان سکشن</h2>
                <p id="dialog-info">This is dynamic content that will change for each session.</p>
                </div>
            </div>
        </div>
        
    </div>

{% endblock %}


{% block extra_js %}
    <script>
                // Get the dialog element
        const dialog = document.getElementById("dialog");
        // Get the element where we'll display dynamic info
        const dialogInfo = document.getElementById("dialog-info");
        // Get the close button element
        const closeButton = document.querySelector(".close-button");

        // Add event listeners to all the "زمان" links
        document.querySelectorAll(".show-dialog").forEach(link => {
        link.addEventListener("click", function (event) {
            event.preventDefault(); // Prevent default link behavior

            dialog.style.display = "flex";
            const sectionId = this.getAttribute("data-section-id");
            const timeslotInfo = document.getElementById(`timeslot-info-${sectionId}`);
            if (timeslotInfo) {
                dialogInfo.innerHTML = timeslotInfo.innerHTML;
            }
         });
        });

        // Close button functionality
        document.querySelector(".close-button").addEventListener("click", function () {
        dialog.style.display = "none";
        });


        // Event listener to close the dialog when close button is clicked
        closeButton.addEventListener("click", function () {
        dialog.style.display = "none";
        });

        // Optionally, close the dialog if the user clicks outside the dialog-content
        window.addEventListener("click", function (event) {
        if (event.target === dialog) {
            dialog.style.display = "none";
        }
        });

    </script>
{% endblock %}

templates/financial.html
{% extends 'base.html' %}

{% block title %}
Aphome | اطلاعات مالی
{% endblock %}
{% load static %}


{% block extra_css %}
    <style></style>
{% endblock %}


{% block content %}

<div class="my-courses">
    <div class="balance">
        hello
    </div>

    {% for record in records %}
        
    {% endfor %}
</div>
{% endblock %}


{% block extra_js %}
    <script></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}
    APhome | خانه
{% endblock %}
{% load static %}
{% load jformat %}


{% block extra_css %}
    <style></style>
{% endblock %}


{% block content %}
    <div class="home-wrapper">
        {% for notif in notifs %}
        <div class="notif">
            <h1>{{ notif.title }}</h1>
            <p>{{ notif.description }}</p>
            <div class="informations">
                <p>{{ notif.section.course.title }}</p>
                <p> {{ notif.section.teacher.first_name }} {{ notif.section.teacher.last_name }} | {{ notif.created_at|jformat:"%Y/%m/%d" }}</p>
            </div>
            <button class="button" id="notif-close-btn" style="width: 80px;">بستن</button>
        </div>
        {% endfor %}


        {% for new in news %}
        <div class="news">

            {% if new.news_img %}
            <img src="{{ new.news_img.url }}" alt="{{ new.title }}">
            {% else %}
            <img src="{% static 'default_course_image.jpg' %}" alt="{{ new.title }}">
            {% endif %}
            <h1>{{ new.title }}</h1>
            <p>{{ new.description }}</p>
            <div class="informations">
                <p>نوشته شده توسط : {{ new.author.first_name }} {{ new.author.last_name }}</p>
                <p>{{ new.created_at|jformat:"%Y/%m/%d"  }}</p>

            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}


{% block extra_js %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Get all the buttons with the class 'button' for closing notifications
        const closeButtons = document.querySelectorAll('.button');
    
        closeButtons.forEach(function(button) {
            // Add an event listener for the 'click' event to each button
            button.addEventListener('click', function() {
                // Find the parent notification div with the class 'notif'
                const notif = this.closest('.notif');
                if (notif) {
                    notif.style.display = 'none';  // Hide the notification
                }
            });
        });
    });
</script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="UTF-8" dir="rtl">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAJ | ورود</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="../media/education_graduate_college_university_cap_graduation_icon_262277.ico" type="image/x-icon">


    
</head>
<body>
  {% if messages %}
      <div class="messages" id="messages">
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}" role="alert">
            <h3 style="margin: 0 auto;">{{ message }}</h3>
          </div>
        {% endfor %}
      </div>
      {% endif %}
    <div class="box">
        <h2>خانه برنامه نویسان اهواز</h2>
            <h3>صفحه ورود دانشجو </h3>

        <form method="POST" action="">
          {% csrf_token %}
          <div class="user-box">
            <input type="text" name="username" required>
            <label>شماره تلفن</label>
          </div>
          <div class="user-box">
            <input type="password" name="password" required>
            <label>رمز عبور</label>
          </div>
          <div class="buttons">
            <a href="{% url 'register_url' %}" class="button">ثبت نام</a>
            <button class="button" type="submit">ورود</button>
            
          </div>
        </form>




    </div>
    <script src="{% static 'js/base.js' %}"></script>

</body>
</html>

templates/my_courses.html
{% extends 'base.html' %}

{% block title %}
    Aphome | دوره های من
{% endblock %}
{% load static %}
{% load jformat %}

{% block extra_css %}
    <style></style>
{% endblock %}


{% block content %}

<div class="my-courses">

    {% for section in sections %}
    <div class="my-course">
        {% if section.course.course_img %}
        <img src="{{ section.course.course_img.url }}" alt="{{ section.course.title }}">
        {% else %}
        <img src="{% static 'default_course_image.jpg' %}" alt="{{ section.course.title }}">
        {% endif %}

        <h1>{{ section.course.title }}</h1>
        <p>{{ section.teacher.first_name }} {{ section.teacher.last_name }} | {{ section.name }}</p>
        
        {% for timeslot in section.time_slots.all %}
        <p>{{timeslot.get_day_of_week_display}} {{timeslot.timeOfSection}} {{timeslot.place}}</p><br>
        {% endfor %}

        <p>{{ section.exam.exam_time|jformat:"%Y/%m/%d"  }}</p>
        <p>در حال تحصیل</p>
        
    </div>
    {% endfor %}
</div>


{% endblock %}


{% block extra_js %}
    <script></script>
{% endblock %}

templates/my_degrees.html
{% extends 'base.html' %}

{% block title %}
Aphome | مدارک من
{% endblock %}
{% load static %}


{% block extra_css %}
    <style></style>
{% endblock %}


{% block content %}

<div class="my-courses">

    {% for degree in degrees %}
    <div class="my-course" style="height: fit-content;">
        {% if degree.course.course_img %}
        <img src="{{ degree.course.course_img.url }}" alt="{{ degree.course.title }}">
        {% else %}
        <img src="{% static 'default_course_image.jpg' %}" alt="{{ degree.course.title }}">
        {% endif %}

        <h1>{{ degree.course.title }}</h1>
        _________________________
        <p style="padding-top: 10px">{{ degree.teacher.first_name }} {{ degree.teacher.last_name }} | {{ section.name }}</p>
        
        _________________________
        <h5 style="padding: 10px;">زمان کلاس ها</h5>
        {% for timeslot in section.time_slots.all %}
        <p>{{timeslot.get_day_of_week_display}} {{timeslot.timeOfSection}} {{timeslot.place}}</p><br>
        {% endfor %}

        _________________________
        <h5 style="padding: 10px;">تاریخ دوره</h5>
        <p>{{ degree.exam.first.exam_time|date:"Y/m/d ساعت H:i"  }}</p>


        _________________________
        <h5 style="padding: 10px;">حضور و غیاب</h5>
        <p>جلسات برگزار شده : {{ section.session_number }} جلسه</p>
        <p>تعداد غیبت ها : {{ section.attendance_count }}

        </p>


        
    </div>
    {% endfor %}
</div>
{% endblock %}


{% block extra_js %}
    <script></script>
{% endblock %}